### ISSUE TITLE
TFAR script error

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#12]

**Comment by nomisum** [comment]
<img width="421" alt="Bildschirmfoto 2021-03-30 um 09 45 56" src="https://user-images.githubusercontent.com/500164/112966023-1d4b1780-914a-11eb-9a82-792e271b3abb.png">

**Comment by dedmen** [comment]
Sieht aus wie TFAR script aus scheduled script gecalled.
Wrap in isNil {};

Arma mit `-debug` parameter starten um den callstack zu sehen um zu sehen wo in eurem code das ist.

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_TracksNTraps.ruha/commit/97bdd817b113b19e7e439e44a0a4d344351259d4
