### ISSUE TITLE
Map / GPS öffnen führt zu Crash

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#15]
Issue bei Map:
[RPT von Zarrck](https://pastebin.com/uUEKfsSv)

Issue beim GPS:
[RPT von DerZade](https://pastebin.com/vQvMtS3x)

**Comment by nomisum** [comment]
![Screenshot 2021-04-09 220354](https://user-images.githubusercontent.com/500164/114237903-0bf0df00-9984-11eb-839f-8fb0c46a39f7.png)

**Comment by DerZade** [comment]
Seems to be an engine problem, which is hopefully fixed in the profiling branch according to Dedmen. I'll close this ticket. We can reopen it, if the issue reappears. :)
