### ISSUE TITLE
Respawned vehicles show up as "Unkown"

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#32]
All vehicles show up as an "unkown" on BFT

![](https://i.imgur.com/r8goSPL.png)

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer/commit/e5339db2a30f84213d6733b8f3408df4e2b669e9

**Comment by nomisum** [comment]
fixed in testgame
