### ISSUE TITLE
Taxis collision check

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#34]
Taxis can spawn at exaclty the same position. So spawning multiple taxis cause explosives

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer/commit/6c4ff9dd2163b2628138332297f0051fc3f31b88

**Comment by nomisum** [comment]
fixed in test game
