### ISSUE TITLE
Destroyed vehicles still have ACE Actions 

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#40]
![20210411205135_1](https://user-images.githubusercontent.com/12705416/114317333-e12f9380-9b07-11eb-869e-ab5d84f346be.jpg)

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer/commit/6bfe2c4c20b3342ced0416f8a9e2701971d1743a and before
