### ISSUE TITLE
Balance request: G3 sights

### ISSUE THREAD

**Issue by Zarrck** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#59]
Change out G3 Iron Sights with something that actually provides vision

**Comment by DerZade** [comment]
This would only encourages infantry combat, which - in my opinion - we should not.

**Comment by Zarrck** [comment]
Infantery combat is going to happen anyways. Additionaly Opfor already has AKs with excellent iron sights so this would only level the playing field.

**Comment by DerZade** [comment]
How about removing primary weapons completely? That would level the playing field as well, and furthermore discourage Rambo behavior in a Tank TvT mode.

**Comment by Zarrck** [comment]
By that Logic you would also have to remove the (imo very cool and probably key) feature to blow up tanks by attaching explosives. 

The only reason infantry combat is going to happen is basically when two crews disable each other at close range and then duke it out to see who gets to blow up the other tank. (Which also led to some of the coolest moments for me in two of the three times I played the mode so far.) Against a fully functioning tank with alert crew infantry is never going to be a threat anyways. Certainly not with their primary weapons.

**Comment by nomisum** [comment]
there seems to be no compatible 1x optic available i fear (inside current dependencies at least)

**Comment by Zarrck** [comment]
There is an 3CB Factions G3A3 that can mount 1x sights, there is also the GM G3A4 EBR, featuring a Picatinny rail and with it the ability to mount basically anything, including 1x sights

**Comment by nomisum** [comment]
there is no 3cb factions in TnT 🗡️, neither RHS which offers some more variety.

the only fitting vanilla optic for the EBR is the optic_aco which .. well i dont know, looks not very authentic i guess 

![20210628134522_1](https://user-images.githubusercontent.com/500164/123631602-39c52180-d817-11eb-8a14-c94ae2cab780.jpg)
