### ISSUE TITLE
Marker Timestamps

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/TvT_TracksNTraps.gm_weferlingen_summer#62]
I wasn't able to automatically add a timestmap to my map markers.

This may be linked to #61

**Comment by nomisum** [comment]
@DerZade might be an issue of our locked ace version - not sure if i can merge the vehicledamage PR into a newer one.

**Comment by DerZade** [comment]
After further investigation @nomisum suspicion turned out to be correct.
